bump bbs rep
[finishes #102329914]

Submodule src/github.com/cloudfoundry-incubator/bbs 49411c5..1957b0b:
  > Add a ping endpoint that the rep can hit to gate evacuation
Submodule src/github.com/cloudfoundry-incubator/rep f0ef73a..e03ec97:
  > Update evacuation handler to use bbs ping timeout

diff --git a/jobs/rep/templates/drain.erb b/jobs/rep/templates/drain.erb
--- a/jobs/rep/templates/drain.erb
+++ b/jobs/rep/templates/drain.erb
@@ -41,6 +41,6 @@ if evacuate; then
   echo 0 >&3
   exit 0
 else
-  echo "$(date): rep exited"
-  echo 0 >&3
+  echo "$(date): evacuation failed"
+  exit 1
 fi
