bump executor garden garden-linux inigo stager
Submodule src/github.com/cloudfoundry-incubator/executor fb051dd..7d04639:
  > Handle new garden client HandleStreamIn/HandleStreamOut api
Submodule src/github.com/cloudfoundry-incubator/garden 7b1683a..9613211:
  > remove unused fake_api_client
  > pass user from StreamInSpec and StreamOutSpec to backend
  > refactor API to use StreamInSpec and StreamOutSpec
Submodule src/github.com/cloudfoundry-incubator/garden-linux 2c2eb38..4d323a0:
  > Remove cruft from previous commit.
  > Add capcheck tool for inspecting capabilities.
  > Always runtime.LockOSThread in init()
  > drop capabilies from inheritable, permitted and effective sets in addition to bounding set
  > Backfill NetIn tests
  > Mount /proc as Read-Only in an unprivileged container
  > Backfill integration test for PR#47.
  > leave longer sleep when checking instance state
  > remove excessive logging
  > Wait for AWS EC2 initialization before run garden tests
  > StreamIn returns appropriate errors when user invalid
  > StreamIn and StreamOut default to root when no user specified
  > StreamIn and StreamOut use spec objects that include user. works same as before with a valid user
  > Faster creation of btrfs loopback in non-nested testing
  > Remove atlas and docker hub workarounds when using packer
  > use newer stdlib crypto library for creating layer ids
  > Remove left-over comments
  > Upgrade docker dependencies to version 1.7.0
  > Fix failing tests. Add integration test to cover capabilities.
  > Add CAP_CHOWN to the list of default capabilities.
  > Add struct to manage setting capabilities.
  > Add LockOSThread in initc's main.
  > Drop capabilities in initc for non-privileged containers.
  > Getting quota info when there is no limit does not fail
  > Metrics() does not error when network stats cannot be read
  > Update garden-ci version to v0.4.1, to fix the lack of preexisting_users rootfs.
  > Avoid race in tests.
  > replace panics with error logging in container_daemon/process.go
Submodule src/github.com/cloudfoundry-incubator/inigo 869fe69..815a156:
  > Fix formatting of expectations
  > Revert "Revert "Revert "Revert "Add new GardenRunner as garden no longer provides one""""
Submodule src/github.com/cloudfoundry-incubator/stager bdbaf1f..5492d4c:
  > Docker staging should run in a Privileged container

diff --git a/jobs/garden-linux/templates/garden-linux_ctl.erb b/jobs/garden-linux/templates/garden-linux_ctl.erb
--- a/jobs/garden-linux/templates/garden-linux_ctl.erb
+++ b/jobs/garden-linux/templates/garden-linux_ctl.erb
@@ -7,6 +7,35 @@ DATA_DIR=/var/vcap/data/garden-linux
 
 source /var/vcap/packages/pid_utils/pid_utils.sh
 
+# copied from https://github.com/concourse/concourse/blob/master/jobs/baggageclaim/templates/baggageclaim_ctl.erb#L54
+# break out of bosh-lite device limitations
+function permit_device_control() {
+  local devices_mount_info=$(cat /proc/self/cgroup | grep devices)
+
+  if [ -z "$devices_mount_info" ]; then
+    # cgroups not set up; must not be in a container
+    return
+  fi
+
+  local devices_subsytems=$(echo $devices_mount_info | cut -d: -f2)
+  local devices_subdir=$(echo $devices_mount_info | cut -d: -f3)
+
+  if [ "$devices_subdir" = "/" ]; then
+    # we're in the root devices cgroup; must not be in a container
+    return
+  fi
+
+  if [ ! -e /tmp/devices-cgroup ]; then
+    # mount our container's devices subsystem somewhere
+    mkdir /tmp/devices-cgroup
+    mount -t cgroup -o $devices_subsytems none /tmp/devices-cgroup
+  fi
+
+  # permit our cgroup to do everything with all devices
+  echo a > /tmp/devices-cgroup${devices_subdir}/devices.allow
+}
+
+
 case $1 in
 
   start)
@@ -42,30 +71,43 @@ case $1 in
     graph_path=$DATA_DIR/graph
 
     <% if p("diego.garden-linux.mount_btrfs_loopback") %>
-      backing_store=$DATA_DIR/garden_graph_backing_store
-      loopback_device=/dev/garden_graph_root
-      mount_point=$graph_path
+    backing_store=/var/vcap/data/garden/garden_graph_backing_store
+    mount_point=$graph_path
 
-      if [ ! -f $backing_store ]
-      then
-        echo "no backing store found at ${backing_store}: creating"
-        dd if=/dev/zero of=$backing_store bs=1M count=<%= p('diego.garden-linux.btrfs_store_size_mb') %>
-        rm -f $loopback_device
-        mknod $loopback_device b 7 200
-        losetup $loopback_device $backing_store
-        mkfs.btrfs $backing_store
-      else
-        echo "backing store already exists, skipping creation"
+    if [ ! -f $backing_store ]
+    then
+      permit_device_control
+      for i in $(seq 0 64); do
+        if ! mknod -m 0660 /dev/loop$i b 7 $i; then
+          break
+        fi
+      done
+
+      echo "no backing store found at ${backing_store}: creating"
+      touch $backing_store
+      truncate -s <%= p('diego.garden-linux.btrfs_store_size_mb') %>M $backing_store
+
+      loopback_device=$(losetup -f --show $backing_store)
+      mkfs.btrfs --nodiscard $loopback_device
+    else
+      echo "backing store already exists, skipping creation"
+    fi
+
+    if cat /proc/mounts | grep $mount_point
+    then
+      echo "btrfs already mounted at $mount_point"
+    else
+      loopback_device="$(losetup -j $backing_store | cut -d':' -f1)"
+
+      if [ -z $loopback_device ]; then
+       echo "Cannot find loopback_device for mount point $backing_store">&2
+       exit 1
       fi
 
-      if cat /proc/mounts | grep $mount_point
-      then
-        echo "btrfs already mounted at $mount_point"
-      else
-        echo "mounting btrfs volume"
-        mkdir -p $mount_point
-        mount -t btrfs $loopback_device $mount_point
-      fi
+      echo "mounting btrfs volume"
+      mkdir -p $mount_point
+      mount -t btrfs $loopback_device $mount_point
+    fi
     <% end %>
 
     exec /var/vcap/packages/garden-linux/bin/garden-linux \
