fail manifest generation when `-s` is missing
[finishes #135746641]

Signed-off-by: Nima Kaviani <nkavian@us.ibm.com>

diff --git a/scripts/generate-deployment-manifest b/scripts/generate-deployment-manifest
--- a/scripts/generate-deployment-manifest
+++ b/scripts/generate-deployment-manifest
@@ -157,6 +157,11 @@ else
   fi
 fi
 
+if [[ -z "${sql_settings}" ]]; then
+  >&2 echo "ERROR: SQL Setting stub is missing"
+  argument_error=true
+fi
+
 if [[ ! -z "${sql_settings}" && ! -f "${sql_settings}" ]]; then
   >&2 echo "ERROR: SQL Setting stub '${sql_settings}' is not a regular file"
   argument_error=true
