Check BBS port is available (#878)
Signed-off-by: David Sabeti <david.sabeti@broadcom.com>

diff --git a/jobs/bbs/templates/post-start.erb b/jobs/bbs/templates/post-start.erb
--- a/jobs/bbs/templates/post-start.erb
+++ b/jobs/bbs/templates/post-start.erb
@@ -2,18 +2,27 @@
 
 log_dir=/var/vcap/sys/log/bbs
 
-address=<%= p("diego.bbs.health_addr") %>
+health_address=<%= p("diego.bbs.health_addr") %>
+listen_address=<%= p("diego.bbs.health_addr") %>
+bbs_port=$(echo ${listen_address} | cut -d":" -f2)
 start=`date +%s`
 i=0
 
 # wait up to 25 seconds
 while [ $(( $(date +%s) - 25 )) -lt $start ]; do
   i=$((i + 1))
-  if curl --fail --silent http://$address/ping 1>/dev/null 2>&1
+  if curl --fail --silent http://${health_address}/ping 1>/dev/null 2>&1
   then
-    exit 0
+    # validate BBS port is reserved for BBS
+    command=$(lsof -n -i :${bbs_port} -sTCP:LISTEN |awk 'NR > 1 {print $1}')
+    if [ "${command}" = "bbs" ] || [ -z "${command}" ]
+    then
+      exit 0
+    fi
+    echo "$(date +%Y-%m-%dT%H:%M:%S.%sZ): Another command is listening on BBS port: ${command}"
+    exit 1
   fi
-  echo "$(date +%Y-%m-%dT%H:%M:%S.%sZ): Failed 'curl --fail --silent http://$address/ping' on attempt $i"
+  echo "$(date +%Y-%m-%dT%H:%M:%S.%sZ): Failed 'curl --fail --silent http://${health_address}/ping' on attempt $i"
   sleep 1
 done
 
